#include "core/Worker.hpp" // Changed to match your folder structure
#include <iostream>
#include <cstdlib> // Necessary for the system() function to interact with the OS

/**
 * @brief Constructor: Injects the list of parsed instructions into the worker.
 * @param steps The vector of AutomationStep structs generated by the Parser.
 * @param manager The shared VariableManager instance for resolving variables.
 */
Worker::Worker(const std::vector<AutomationStep>& steps, std::shared_ptr<VariableManager> manager) 
    : steps(steps), varManager(manager) {}

/**
 * @brief The execution loop: Iterates through each task in the sequence.
 * Now integrated with VariableManager to resolve dynamic placeholders 
 * before execution.
 */
void Worker::execute() {
    std::cout << "\n[Worker] Starting Execution Sequence..." << std::endl;
    std::cout << "---------------------------------------" << std::endl;

    for (auto& step : steps) {
        std::string resolvedCommand = step.command;
        
        // Resolve variables if varManager is available
        if (varManager) {
            resolvedCommand = varManager->resolve(step.command);
        }

        step.command = resolvedCommand;
        performAction(step);
    }

    std::cout << "---------------------------------------" << std::endl;
    std::cout << "[Worker] Sequence finished successfully." << std::endl;
}

/**
 * @brief Logic Dispatcher: Interprets the 'actionType' and runs the command.
 * @param step The individual instruction containing the type and the command string.
 */
void Worker::performAction(const AutomationStep& step) {

    // Supports both "shell" and "type" keys from the JSON for maximum compatibility
    if (step.actionType == "shell" || step.actionType == "type") {
        std::cout << "[Worker] Executing: " << step.command << std::endl;

        /**
         * system() sends the command string to the host shell (/bin/sh).
         * .c_str() is used because system() requires a C-style char array (const char*).
         */
        int result = std::system(step.command.c_str());

        // Error handling: In Linux, a non-zero exit code usually indicates failure
        if (result != 0) {
            std::cerr << "[Worker Error] Command failed with code: " << result << std::endl;
        }
    } 
    else {
        // Warning for future-proofing: triggers if your JSON uses an unsupported type
        std::cerr << "[Worker Warning] Unknown action type: " << step.actionType 
                  << ". Skipping command: " << step.command << std::endl;
    }
}